### PR TITLE
Update Recharts (v0.20.1)

### PR DESCRIPTION
**Pull request by danielbayerlein**
`precharts` uses an old version of `recharts`. This PR update the dependencies.

**Changes**
* Add Node.js v7 to `.travis.yml`
* Update dependencies to the latest versions
* Move `recharts` from `"github:billneff79/recharts#v1.1.4",` to `^0.20.1`
* Remove unnecessary `react-container-dimensions`
* Add necessary `react-resize-detector`

A new version of `precharts` would be very nice! Thanks @developit ❤️

### CODE REVIEW

**Comment by developit** [comment]
Looks good to me! I need to compare filesize before and after.

**Comment by danielbayerlein** [comment]
@developit I compared the filesize:

| Type | Before | After |
| ----- | ------ | ----- |
| original | 399 kB | 431 kB |
| minified | 160 kB | 174 kB |
| gzip | 42.4 kB | 46.6 kB |

**Comment by developit** [comment]
@danielbayerlein - think the size bump is just coming in from the upstream Recharts changes? If so then I think we are good to go!

If you want, I'm happy to add you as a collaborator to this project. Really appreciate the effort here!

**Comment by danielbayerlein** [comment]
@developit Yes, the size bump comes from the update.

| Type | Recharts.js (v0.20.1) | Recharts.js Fork (v1.1.4) |
| ----- | ------ | ----- |
| original | 1.11 MB |  1.05 MB |
| minified |  439 kB | 427 kB |

Oh yes, I can help you to maintain this project! My pleasure.

**Comment by developit** [comment]
Invited!

**Pull request merged**
