### PR TITLE
Uses `babel-plugin-lodash` to reduce bundle size

### PR DESCRIPTION
**Pull request by rubencodes**
Shrunk about 25kb off the gzipped bundle size in my tests.

The second commit here was necessary to silence warnings, not sure if it's the _ideal_ solution. Feedback welcome.

### CODE REVIEW

**Comment by billneff79** [comment]
Looks good to me.  Any others have feedback?

**Comment by danielbayerlein** [comment]
@rubencodes Thank you for your PR! Can you please resolve the conflicts?

**Comment by rubencodes** [comment]
I think that should do it! 👍

**Comment by rubencodes** [comment]
*bump* I think this got forgotten 😅

**Comment by danielbayerlein** [comment]
@rubencodes Sorry for the late reply. When I check out your branch, the bundle is the same size as before. That confuses me. Can you please try again and tell me the result?

**Comment by rubencodes** [comment]
Yes, the size improvement isn't in the resulting precharts bundle itself, but rather in the lodash module that's installed alongside it. Instead of pulling in all of lodash (what master does), this branch only pulls in the functions precharts actually uses. The size difference is very apparent when actually installing precharts in a project, but hard to discern just from looking at the precharts bundle.

example

**Comment by danielbayerlein** [comment]
@rubencodes Thank you for the explanation!

**Comment by danielbayerlein** [comment]
I'll release a new version soon. 🎉

**Comment by rubencodes** [comment]
Awesome! Looking forward to it!

**Pull request merged**
